### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by RikoDEV** [NightlySide/SpawnerChangerGUI#2]
- Add option to translate **Spawner Type:**
- Fix llama and evoker eggs (blank)
- Add option to translate mob names?

**Comment by NightlySide** [comment]
I'll take a look tonight
If you have any clue about string translation ? (Like a plugin or a lib)

**Comment by NightlySide** [comment]
I've done the two first things, I'll do maybe the third for the big 1.13 update as I have to rewrite again.
You can expect an update on both spigotMC and DevBukkit websites tonight :)
