### ISSUE TITLE
spawnergui bugchat

### ISSUE THREAD

**Issue by Deernose** [NightlySide/SpawnerChangerGUI#3]
When I break the spawner the message "true" appears in the chat, besides when I break using silktouch drops the spawner, but drops xp together

I'm on 1.12.2
![image](https://user-images.githubusercontent.com/32472199/43664247-a4ce2a6c-9742-11e8-8c8e-4bf3f059d26a.png)

**Comment by NightlySide** [comment]
Thanks for reporting :)
I'll take a look tonight .. maybe it's just a debug thing ^^ 
If you find anything else, tell me 

Nightlyside

**Comment by NightlySide** [comment]
Actually it was a debug thing, you can expect an update on the spigot and DevBukkit website tonight ;)

**Comment by Deernose** [comment]
Tnx sz
